### ISSUE TITLE
[FIX] Tela de sign up - Referência incorreta do arquivo CSS

### ISSUE THREAD

**Issue by brunolcarli** [brunolcarli/MyRoomWebClient#10]
@souzlays 

## Problema

O PR enviado com a alteração da tela de SignUP apresenta inconsistência na renderização do estilo:

![Captura de Tela 2023-10-16 às 01 07 54](https://github.com/brunolcarli/MyRoomWebClient/assets/14935269/f3c2f8cc-5b3a-4cdb-9ef6-b1e4b3c7baf6)

Isso se dá ao fato de a página signup estar contida dentro do um diretorio `pages` e a referencia ao arquivo `style2.css` estar fazendo a chamada do arquivo neste diretorio, porém o mesmo se encontra um diretório acima, na raiz:

![signupFix](https://github.com/brunolcarli/MyRoomWebClient/assets/14935269/cd92e53f-aae5-4e38-abe9-a605bf48665b)

## Sugestão

apontar a referencia par aum diretorio acima:

```diff
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
-    <link rel="stylesheet" href="style2.css">
+    <link rel="stylesheet" href="../style2.css">
    <title>Sign up</title>
</head>
```

**Comment by brunolcarli** [comment]
@souzlays 

O FIX enviado corrige o style css 👍 


![Captura de Tela 2023-10-16 às 10 18 42](https://github.com/brunolcarli/MyRoomWebClient/assets/14935269/0af19a4a-5cee-426d-ad62-e8ba926af803)



Porém, ao clicar no botão **Confirm** nada acontece 🤷 

Isso se dá pelo motivo de no código html do botão de confirmação, o atributo `onclick` não estar definido fazendo a chamada para a função javascript que captura os dados do formulario e envia a requisição para o backend:

![Captura de Tela 2023-10-16 às 10 20 56](https://github.com/brunolcarli/MyRoomWebClient/assets/14935269/414542a3-8c9c-447f-b451-3ce42d44d801)


### Sugestão

Incluir o atributo `onclick` fazendo a chamada para a função `resolve_signup()`

```diff

- <button id="SignupConfirm" class="button-confirm" type="button">Confirm</button>
+ <button id="SignupConfirm" class="button-confirm" type="button" onclick="resolve_signup()>Confirm</button>

```

### ⚠️  Observação importante ⚠️ 

A função `resolve_signup()` está definida no arquivo `resolvers.js` que aparentemente foi removida do header do html, é necessário reinseri-la para que a chamada da função seja executada, assim como reinserir a referência ao arquivo `requests.js`:

![Captura de Tela 2023-10-16 às 10 27 49](https://github.com/brunolcarli/MyRoomWebClient/assets/14935269/c0fac6b0-64e6-47b4-aa98-b15e3964a3f1)

👇 


![Captura de Tela 2023-10-16 às 10 28 12](https://github.com/brunolcarli/MyRoomWebClient/assets/14935269/d07220b8-7377-4f86-b1ca-c9a17350492e)

**Comment by souzlays** [comment]
O sign up funcionou, registrou a conta e encaminha pra tela de login,
porém, a tela de login parou de funcionar.
erros do inspecionar:
[image: Screenshot from 2023-10-16 13-14-00.png]

Em seg., 16 de out. de 2023 às 12:43, Bruno L. Carli <
***@***.***> escreveu:

**Comment by brunolcarli** [comment]
seu print nao aparece aqui
